title = "Kaupungin Naiset"
baseURL = "https://kaupunginnaiset.fi"
languageCode = "fi-FI"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "fi"
SectionPagesMenu = "main"
Paginate = 20
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.fi]
    title = "Kaupungin Naiset"
    weight = 1
    contentDir = "content/fi"
  [languages.en]
    title = "Kaupungin Naiset"
    weight = 2
    contentDir = "content/en"
  [languages.se]
    title = "Kaupungin Naiset"
    weight = 3
    contentDir = "content/se"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "logo-char.png"
  site_logo = "logo-white.png"
  description = "Suomen paras lesbokuoro"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 20
  body_classes = "avenir bg-near-white"

[[params.ananke_socials]]
name = "email"
url = "mailto:info@kaupunginnaiset.fi"
label = "email"
color = "white"

# [[params.ananke_socials]]
# name = "shop"
# url = "https://www.reddyshop.co/kaupunginnaiset"
# label = "shop"
# color = "white"

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/kaupunginnaiset"

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/kaupunginnaiset"

[[params.ananke_socials]]
name = "youtube"
url = "https://www.youtube.com/@kaupunginnaiset"

